---
schedule: &schedule
  schedule:
    interval: "daily"

schedule_group: &schedule_group
  <<: *schedule
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/5.6"
    <<: *schedule_group

  - package-ecosystem: "docker"
    directory: "/7.0"
    <<: *schedule_group

  - package-ecosystem: "docker"
    directory: "/7.1"
    <<: *schedule_group

  - package-ecosystem: "docker"
    directory: "/7.2"
    <<: *schedule_group

  - package-ecosystem: "docker"
    directory: "/7.3"
    <<: *schedule_group

  - package-ecosystem: "docker"
    directory: "/7.4"
    <<: *schedule_group

  - package-ecosystem: "docker"
    directory: "/8.0"
    <<: *schedule_group

  - package-ecosystem: "docker"
    directory: "/8.1"
    <<: *schedule_group

  - package-ecosystem: "docker"
    directory: "/8.2"
    <<: *schedule_group

  - package-ecosystem: "github-actions"
    directory: "/"
    <<: *schedule
